- lib/Cargo.toml
- lib/Makefile
- lib/flutter/ios/Classes/DIDKitFlutterPlugin.m
- lib/flutter/ios/didkit.podspec
- lib/flutter/pubspec.lock
Here are the changes I made to support iOS on Flutter.
- Add `staticlib` to the crate;
- Add `*.a` files to podspec and set `static_framework=true`;
- Add dummy method call so the lib doesn't get excluded;
- Add targets to Makefile to install targets and build and bundle the libs.
[Unfortunately, `rust` has dropped support for `armv7-apple-ios`, `armv7s-apple-ios` and `i386-apple-ios`.](https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html)
So we can only build and bundle `aarch64-apple-ios` and `x86_64-apple-ios`.
> iOS Support

- CHANGELOG.md
- cli/Cargo.toml
- http/Cargo.toml
- lib/Cargo.toml
Add changelog in the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), as mentioned in https://github.com/spruceid/ssi/issues/23#issuecomment-686015818).
Cargo uses Semantic Versioning, so it makes sense to use that:
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
- https://doc.rust-lang.org/cargo/reference/semver.html
I dated the release in the changelog to the date of the announcement blog post.
The packages `didkit`, `dikdit-cli`, and `didkit-http` are all incremented from `0.0.1` to `0.1.0`.
**Edit**: this PR includes a commit intended for tagging as a release. To ensure correspondance with the initial release blog post, this commit should not rebased.
> Add Changelog and release

- .github/workflows/build.yml
CI access token is no longer needed for cloning `ssi` and `vc-http-api` since they are public.
> Remove CI access token

- .github/workflows/build.yml
- cli/Cargo.toml
- http/Cargo.toml
- lib/Cargo.toml
Integrate https://github.com/spruceid/ssi/pull/85
This is to allow `didkit-wasm` (#52) to depend on `ssi` without bringing in `ring`, while still using `ring` in the other crates (CLI, HTTP, FFIs), and allowing other dependents to pick their own.
> Keep ssi features optional

- .github/workflows/build.yml
- Cargo.toml
- lib/Makefile
- lib/node/.gitignore
- lib/node/README.md
- lib/node/lib/index.js
- lib/node/native/.gitignore
- lib/node/native/Cargo.toml
- lib/node/native/build.rs
- lib/node/native/src/didkit.rs
- lib/node/native/src/error.rs
- lib/node/native/src/lib.rs
- lib/node/native/src/macros.rs
- lib/node/package-lock.json
- lib/node/package.json
- lib/node/test/index.spec.js
Add Node.js support with `neon-bindings`.
Added build and test targets on `lib/Makefile`.
This is a substitute for #17.
> Add Node.js support with `neon-bindings`

- .github/workflows/build.yml
- Cargo.toml
- lib/Cargo.toml
- lib/Makefile
- lib/src/lib.rs
- lib/wasm/.gitignore
- lib/wasm/Cargo.toml
- lib/wasm/DEPS.md
- lib/wasm/README.md
- lib/wasm/loader/.eslintrc.js
- lib/wasm/loader/.gitignore
- lib/wasm/loader/didkit-loader.js
- lib/wasm/loader/didkit_wasm_bg.wasm
- lib/wasm/loader/index.html
- lib/wasm/loader/package-lock.json
- lib/wasm/loader/package.json
- lib/wasm/loader/test/index.test.js
- lib/wasm/loader/webpack.config.js
- lib/wasm/src/lib.rs
Adds WASM support to DIDKit using `wasm-pack`/`wasm-bindgen`.
Added a `wasm` feature on DIDKit to prevent compiling C and Java integration on the `wasm-pack` build.
Added `DIDKitLoader` for web targets to facilitate working with the WASM code on browsers.
Added a test for all current methods on DIDKit using `DIDKitLoader` and the WASM build.
This is a substitute for #15.
> Add WASM Support

- lib/flutter/.gitignore
- lib/flutter/analysis_options.yaml
- lib/flutter/lib/didkit.dart
- lib/flutter/pubspec.lock
- lib/flutter/pubspec.yaml
- lib/flutter/test/didkit_test.dart
I was updating dependencies on Credible in preparation for the upcoming Dart [nullsafety](https://dart.dev/null-safety/migration-guide) and ended up having to also update the `ffi` version on the library to match. I took the liberty to also add the same lint options I'm using on Credible, update .gitignore, and remove the default example.
> Flutter Library Updates

- .github/workflows/build.yml
Attempt to fix build error in CI:
> Because didkit requires SDK version >=2.11.0 <3.0.0, version solving failed.
> The current Dart SDK version is 2.10.5.
https://github.com/spruceid/didkit/runs/1856876167#step:24:26
> Use Flutter dev channel

- README.md
`cargo build` in the repo root directory builds all the packages in the workspace. Since #55 this results in enabling conflicting features for cryptographic backends in `ssi`. This PR updates the readme to say to build the workspace excluding the `didkit-wasm` crate - so that the `ssi` features needed for WASM (which conflict with the default `ssi` features) are not enabled at the same time.
I'm also open to suggestions on other ways to make this better.
> Exclude didkit-wasm in build instructions

- .github/workflows/build.yml
- Cargo.toml
- README.md
As suggested by @theosirian in https://github.com/spruceid/didkit/pull/62#issuecomment-775938615: this sets the `default-members` workspace config property to the existing workspace members except for `didkit-wasm`. This enables using `cargo build` in the repo root directory - a common command for a user to tun - without causing incompatible `ssi` features to be enabled. CI is also updated to use
`cargo build --verbose`. Fixes https://github.com/spruceid/didkit/issues/63
> Set default workspace members excluding WASM

- http/Cargo.toml
We can use hyper v0.14.3 if enabling http2, as described here:
https://github.com/hyperium/hyper/issues/2421
Closes #56, closes #57
> Enable http2

- Cargo.toml
I am removing this member to strip external nodejs dependencies from the default `cargo build` command.
> Remove node build from default-members

- .github/workflows/build.yml
- cli/Cargo.toml
- cli/README.md
- cli/src/lib.rs
- cli/src/main.rs
- cli/src/opts.rs
- cli/tests/cli.rs
- cli/tests/example.sh
- http/Cargo.toml
- http/README.md
- http/src/lib.rs
- http/src/main.rs
- http/tests/example.sh
- http/tests/main.rs
- lib/Cargo.toml
- lib/c/test.c
- lib/flutter/lib/didkit.dart
- lib/flutter/test/didkit_test.dart
- lib/java/main/com/spruceid/DIDKit.java
- lib/java/test/com/spruceid/DIDKitTest.java
- lib/src/c.rs
- lib/src/jni.rs
- lib/src/lib.rs
New commands, with corresponding FFI functions:
- `did-resolve` - [Resolve a DID to a DID document](https://w3c-ccg.github.io/did-resolution/#resolving).
- `did-dereference` - [Dereference a DID URL to a resource](https://w3c-ccg.github.io/did-resolution/#dereferencing).
New HTTP route:
- `/identifiers/<uri>` - Resolve a DID or dereference a DID URL, according to the [DID Resolution HTTP(S) Binding][did-resolution-https-binding].
New CLI option for `didkit-cli` and `didkit-http`:
- `-r` (`--did-resolver`) - URL of a [DID resolver HTTP(S) endpoint]. Used as a fallback resolver to resolver DIDs and dereference DID URLs for DID methods not built-in to DIDKit.
The DID Resolution HTTP(S) Binding as implemented here is compatible with the [Universal …
> Add DID Resolution commands and option

- .github/workflows/push_image.yml
This should have been included in #54.
This should fix the build error seen in https://github.com/spruceid/didkit/runs/1865533845 since I removed the token from the repo settings.
> Remove obsolete access token

- .github/workflows/build.yml
- cli/tests/example.sh
- http/tests/example.sh
This enables using the CLI and HTTP `example.sh` script with other DID methods besides `did:key` that can be derived from a JWK. Using these with `did:tz` is added to the CI.
Depends on https://github.com/spruceid/ssi/pull/92
> Make example.sh DID method configurable

- cli/Cargo.toml
- cli/src/main.rs
- lib/Cargo.toml
- lib/node/native/Cargo.toml
- lib/node/native/src/didkit.rs
- lib/node/native/src/error.rs
- lib/src/c.rs
- lib/src/error.rs
- lib/src/jni.rs
- lib/src/lib.rs
- lib/src/runtime.rs
- lib/wasm/Cargo.toml
Using `hyper` for HTTP(S) requires a [`tokio` Runtime](https://docs.rs/tokio/1.2.0/tokio/runtime/struct.Runtime.html).
This PR updates the FFI code to set up a Tokio runtime for FFI calls and use the runtime's [`block_on`](https://docs.rs/tokio/1.2.0/tokio/runtime/struct.Runtime.html#method.block_on) function instead of `async-std`'s [`block_on`](https://docs.rs/async-std/1.9.0/async_std/task/fn.block_on.html). This is needed for resolving `did:web` DIDs since that uses `hyper`, which would otherwise `panic` about not being run in a Tokio runtime.
For performance reasons, I set the FFI functions to use Tokio's [current-thread scheduler](https://docs.rs/tokio/1.2.0/tokio/runtime/struct.Runtime.html#current-thread-scheduler), to avoid spawning threads on each call. If we eventually need the …
> Use tokio runtime

- .github/workflows/build.yml
- lib/Cargo.toml
- lib/src/did_methods.rs
- lib/src/lib.rs
- lib/wasm/Cargo.toml
- lib/wasm/src/lib.rs
Depends on: https://github.com/spruceid/ssi/pull/99
This adds functions to DIDKit's WASM API for credential issuance with external signing. This approach splits issuance into two parts, one is everything up to the cryptographic signing, and the other is everything after. There are two functions added, one to prepare issuing a credential, and another to complete issuing the credential. The `prepareIssueCredential` function returns a [`ProofPreparation`](https://github.com/spruceid/ssi/blob/29bbbe1d7a5bd1825d71c05dc083bef7fbd075f1/src/ldp.rs#L76-L80) object which includes the data to sign. The `completeIssueCredential` function takes this proof preparation and the signed data along with same credential and returns the credential issued with the completed proof.
These functions are only …
> Enable external signing for WASM and did:ethr

- .github/workflows/build.yml
- cli/src/main.rs
- cli/tests/cli.rs
- cli/tests/example.sh
- lib/c/test.c
- lib/flutter/lib/didkit.dart
- lib/flutter/pubspec.lock
- lib/flutter/pubspec.yaml
- lib/flutter/test/didkit_test.dart
- lib/java/main/com/spruceid/DIDKit.java
- lib/java/test/com/spruceid/DIDKitTest.java
- lib/node/native/src/didkit.rs
- lib/node/native/src/lib.rs
- lib/node/package-lock.json
- lib/node/package.json
- lib/node/test/index.spec.js
- lib/src/c.rs
- lib/src/jni.rs
- lib/wasm/loader/test/index.test.js
- lib/wasm/src/lib.rs
Depends on: https://github.com/spruceid/ssi/pull/105
A DIDAuth command/function is added to:
- CLI
- C
- JNI
- Flutter/Dart
- Node
- WASM
- tests
- CLI readme
I didn't add it to the HTTP interface because this is not specified in the VC HTTP API or DID Resolution HTTP(S) Binding.
The DIDAuth function takes a holder URI (e.g. a DID), linked data proof options (same as for issuing a credential or presentation), and a JWK, and generates a [Verifiable Presentation](https://w3c.github.io/vc-data-model/#presentations-0) (which does not contain a `verifiableCredential`).
Reference: https://w3c-ccg.github.io/vp-request-spec/#did-authentication-request
> Implement DIDAuth

- lib/wasm/loader/webpack.config.js
Attempt to fix #87
The webpack configuration file didn't need the `wasm-loader` section.
Probably forgot to remove that when I made the PR for WASM.
> Fix Webpack config file for didkit-loader (wasm)

- lib/Makefile
- lib/wasm/README.md
- lib/wasm/asm/.gitignore
- lib/wasm/asm/asm-loader.js
- lib/wasm/asm/didkit_wasm_bg.js
- lib/wasm/asm/didkit_wasm_bg1.js
- lib/wasm/asm/package-lock.json
- lib/wasm/asm/package.json
- lib/wasm/asm/repack.sh
- lib/wasm/asm/webpack.config.js
This PR adds the possibility of building ASM targets from wasm. As part of the build process an external dependency was needed to be added [binaryen](https://github.com/WebAssembly/binaryen). The necessary build steps were described in the README
> Adds ASM build target

- lib/node/README.md
Small update, that can hopefully help someone perusing the node side of didkit. 💪 🎉 
Updates the node readme code sample to use proper arguments for `key-to-did` & `key-to-verification-method` for `keyToDID` and `keyToVerificationMethod` respectively. 
These functions require passing in the did method, in this case, "key". Other currently supported did method is "web" according to [CLI docs](https://github.com/spruceid/didkit/blob/main/cli/README.md#didkit-key-to-did-method_name).
> Update didkit-node README code sample

- lib/Makefile
This makes possible to use the build target on Windows machines, since it's folders have spaces in the names.
> Add double quote to work on Windows

- lib/java/test/com/spruceid/DIDKitTest.java
While looking at the current test files for reference for a test file for Go, I noticed that the Java tests included two checks using the wrong variable.
> Fix Variable Naming in Java Tests

- cli/README.md
- http/README.md
- http/src/lib.rs
- http/tests/example.sh
- http/tests/main.rs
`vc-http-api` adopted controller pattern routes in v0.0.2-unstable: https://github.com/w3c-ccg/vc-http-api/pull/73
This PR updates `didkit-http` to use `vc-http-api v0.0.2-unstable`'s routes. The `vc-http-api v0.0.1` routes are left in, for backwards-compatibility, but documentation and examples are updated to use the `v0.0.2-unstable` routes.
> Use vc-http-api controller pattern

- .github/workflows/build.yml
The CI Environment already includes Android SDK/NDK:
https://github.com/actions/virtual-environments/blob/ubuntu20/20210315.1/images/linux/Ubuntu2004-README.md#environment-variables-3
By using the Android SDK/NDK included in the environment rather than installing it separately, we save some space (#108) and time (#69).
> Use default Android SDK/NDK in CI

- .github/workflows/build.yml
Similar to #110, this reduces disk usage and time in CI by using the [environment's JDK](https://github.com/actions/virtual-environments/blob/ubuntu20/20210315.1/images/linux/Ubuntu2004-README.md#java). Note that the default is version 11, while we previously have been using version 8.
> Use system's JDK in CI

- README.md
Belated change to the images visibility. Apologies to anyone who tried to use them before.
> Container images are now public

- lib/cbindings/Cargo.toml
- lib/node/native/Cargo.toml
For consistency, update the `wasm` and `cbindings` package names to use hyphenation.
- `didkit_wasm` → `didkit-wasm`
- `didkit_cbindings` → `didkit-cbindings`
> Hyphenate package names

- .github/workflows/build.yml
- .github/workflows/push_image.yml
Fix #130
`ssi` since https://github.com/spruceid/ssi/pull/138 depends on a git submodule for `json_ld`
> Checkout ssi with submodules

- cli/README.md
- cli/src/main.rs
- lib/flutter/lib/didkit.dart
- lib/java/main/com/spruceid/DIDKit.java
- lib/node/native/src/didkit.rs
- lib/python/didkit/__init__.py
- lib/src/c.rs
- lib/src/jni.rs
- lib/web/src/lib.rs
Change method name to method pattern for `key-to-did` and `key-to-verification-method` and corresponding FFI functions.
Method pattern is a generalization of method name that allows passing an additional string to the DID method by appending it to the DID method name, separated by a colon (`:`). This can be used to request generating a DID under a given prefix or other pattern if supported by the DID method.
Depends on: https://github.com/spruceid/ssi/pull/133
This is intended to enable https://github.com/spruceid/didkit/pull/115, to be used like this:
`didkit key-to-did pkh:tz`
This allows reusing the existing API.
An alternative would be to use a metadata/options structure, like this:
`didkit key-to-did pkh -i publicKeyHashName=tz`
That is more verbose, and would require changing the …
> Generate DID with method pattern

- lib/Cargo.toml
- lib/src/did_methods.rs
Uses https://github.com/spruceid/ssi/pull/147
This should work, returning a DID document:
```
$ didkit did-resolve did:onion:fscst5exmlmr262byztwz4kzhggjlzumvc2ndvgytzoucr2tkgxf7mid
```
~~Note that we cannot use the resulting DID document as-is, due to https://github.com/spruceid/ssi/issues/148. It might also be a problem that this particular DID document uses a property `VerificationMethod` instead of `verificationMethod`.~~ The document is fixed: https://github.com/spruceid/didkit/pull/125#issuecomment-810634276
This should fetch and verify a VC (Thanks @gorazdko for the example VC):
```
curl -sx socks5h://127.0.0.1:9050/ http://fscst5exmlmr262byztwz4kzhggjlzumvc2ndvgytzoucr2tkgxf7mid.onion/vc_sw2.json | didkit vc-verify-credential
```
~~Should we test this live in CI, connecting to an …
> Add did:onion

- CHANGELOG.md
Prepare for `v0.2.0` release: #119 
See also: `ssi` Changelog updates https://github.com/spruceid/ssi/pull/143
> Update Changelog with changes since v0.1.0

- cli/tests/cli.rs
- http/tests/main.rs
- lib/Cargo.toml
For #138, in order to provide the most functionality we can for the Universal Resolver, it would be useful to enable secp256k1 and p256 features for the `didkit-http` Docker image. As mentioned in https://github.com/spruceid/didkit/issues/138#issuecomment-816126213, these features are currently not enabled by default. I think it would be good to make these default features for `didkit`, `didkit-cli`, and `didkit-http`, so that users are not surprised by missing functionality. The features should remain opt-out-able via disabling `default-features`.
> Enable secp256k1 and p256 by default

- .github/workflows/build.yml
- lib/Makefile
Python build command no longer will install after build, instead a new target was added `install-python` which installs, and builds if not already, the wheel to the current `pip`.
> Move install from Python build to a new target

- lib/Cargo.toml
Progress for #119
- Add package metadata.
- Include only the Rust source files in the crate, not all the other things in `/lib`.
- Depend on ssi crates using their `crates.io` registry versions.
Publish dry-run succeeds with this command:
```
$ cargo publish --dry-run --manifest-path lib/Cargo.toml
```
> Prepare didkit crate for publishing to crates.io

- CHANGELOG.md
- lib/Cargo.toml
- lib/python/setup.cfg
Increment crate version and update changelog.
Includes #139
Also update the Python package version, since tests expect it to match the `didkit` crate's version.
Release command for publish to `crates.io` registry:
```
cargo publish --manifest-path lib/Cargo.toml
```
To be followed by creating a signed git tag including the content hash of the crate.
> didkit 0.2.0

- cli/Cargo.toml
- http/Cargo.toml
Prepare for publish to crates.io. Progress for #119
Update package metadata. Exclude tests directories to remove files not needed in the crate release.
Dry-run publish of didkit-cli succeeds. Files:
```
$ tar tzf target/package/didkit-cli-0.1.0.crate
didkit-cli-0.1.0/.cargo_vcs_info.json
didkit-cli-0.1.0/Cargo.lock
didkit-cli-0.1.0/Cargo.toml
didkit-cli-0.1.0/Cargo.toml.orig
didkit-cli-0.1.0/LICENSE
didkit-cli-0.1.0/README.md
didkit-cli-0.1.0/src/lib.rs
didkit-cli-0.1.0/src/main.rs
didkit-cli-0.1.0/src/opts.rs
```
`didkit-http` publish does not work yet because it depends on `didkit-cli` being published, but I've added the changes I expect will enable it to work otherwise.
> Update didkit-cli and didkit-http package metadata

- .github/workflows/build.yml
Update to use ssi v0.2.1 and did-method-key v0.1.1 in CI, to fix
`simple_asn1`/num-bigint type mismatch build failure seen in https://github.com/spruceid/didkit/runs/2451568678
Mentioned in https://github.com/spruceid/didkit/pull/155#issuecomment-828758249
> Update ssi ref

- lib/node/lib/index.d.ts
@w4ll3
While working on the gitcoin example we added the typescript type declarations to avoid lint issues when importing.
> Add typescript type declaration

- lib/node/package.json
Previous `package.json` included `index.node` instead of `index.d.ts`.
> [Node] Update package files and version

- lib/Cargo.toml
- lib/Makefile
- lib/flutter/ios/Classes/DIDKitFlutterPlugin.m
- lib/flutter/lib/didkit.dart
- lib/flutter/libdidkit.dylib
- lib/flutter/test/didkit_test.dart
Fixes spruceid/credible#51 
1. cargo outputs a `.dylib` file on macOS hosts, I updated the Makefile to support both `dylib` and `so` files.
**I'm not a specialist on Makefiles, maybe there's a better way of accomplishing that.**
2. I've added all functions from `didkit.h` to the `didkit/lib/flutter/ios/Classes/DIDKitFlutterPlugin.m` file, cause they were being removed on release builds as they are not called anywhere.
**I manually added those functions and I think this is not the best way of doing this, maybe a better way would be some form of automation, every time the `didkit.h` changes, it automatically changes the `DIDKitFlutterPlugin.m`.**
If someone knows a better way of doing this, please suggest on the PR.
> Fix build on apple platforms and fix ios release builds

- lib/flutter/ios/didkit.podspec
* Set the iOS deployment target of the flutter lib to 11.0
Rust doesn't generate a library for `armv7-apple-ios` target, that is needed for iOS version less than 11 (older devices runs armv7 architecture), so we can bump the minimum version of the flutter lib to iOS 11 (the first version that doesn't support armv7)
> Set iOS deployment target to 11.0

- cli/src/main.rs
This change allows the LinkedDataProofOptions struct to gain more properties, as happened in https://github.com/spruceid/ssi/pull/213.
> Use Default with LinkedDataProofOptions

- .github/workflows/build.yml
- cli/src/main.rs
- cli/tests/cli.rs
- cli/tests/example.sh
- http/src/lib.rs
- http/tests/example.sh
- http/tests/main.rs
- lib/Cargo.toml
- lib/c/test.c
- lib/java/test/com/spruceid/DIDKitTest.java
- lib/node/src/didkit.rs
- lib/src/c.rs
- lib/src/error.rs
- lib/src/jni.rs
- lib/src/lib.rs
- lib/web/loader/wasm/test/index.test.js
- lib/web/src/lib.rs
Fix #149. This is to implement support for JWT VCs and VPs using the existing API.
Conflicts with #158. Depends on https://github.com/spruceid/ssi/pull/201
> Improve JWT VC/VP support

- .github/workflows/build.yml
- cli/Cargo.toml
- cli/README.md
- cli/src/main.rs
- cli/tests/ssh-agent.sh
- lib/Cargo.toml
- lib/src/did_methods.rs
- lib/src/lib.rs
- lib/src/ssh_agent.rs
Close #154
Depends on: https://github.com/spruceid/ssi/pull/178
- #173 
- #174
> Add did:webkey and sign with ssh-agent functionality

- lib/python/didkit/__init__.py
- lib/python/setup.cfg
- lib/python/setup.py
The current python build process includes a hardcoded filepath to the libdidkit shared object that the python library relies upon: https://github.com/spruceid/didkit/blob/171c99ac2db8276828b2141b0a9ac6be8a580a19/lib/python/setup.cfg#L25 
The hardcoding assumes the python library is being built on a Linux system and the file will have a `.so` extension. Buidling on macOS fails as the python build script tries to copy `libdidkit.so` which doesn't exist, instead it should try to copy `libdidkit.dylib`.
Given the required shared object depends on the system being built it needs to be dynamically determined and has to go into a setup.py rather than being able to defined in a setup.cfg.
Boilerplate fix attached but there a variety of ways to solve this one for sure.
> Fix for statically defined options.data_files build variable for Python library build

- cli/src/main.rs
- cli/tests/.gitignore
- cli/tests/cli.rs
- cli/tests/example.sh
This adds a CLI subcommand for converting JSON-LD to canonicalized RDF, to address #163.
1. Perform context expansion of JSON-LD document.
2. Deserialize JSON-LD document to RDF dataset.
3. Canonicalize dataset using [URDNA2015](https://json-ld.github.io/rdf-dataset-canonicalization/spec/).
4. Serialize dataset in [N-Quads](https://www.w3.org/TR/n-quads/) format.
This exposes the functionality used internally by many [linked data signature](https://w3c-ccg.github.io/ld-proofs/) [suites](https://w3c-ccg.github.io/ld-cryptosuite-registry/). It can be useful for inspecting the data contents of a verifiable credential or presentation, [linked data authorization capability](https://w3c-ccg.github.io/zcap-ld/), or other linked data document.
Another use for this sub-command is to construct …
> Add to-rdf-urdna2015 subcommand

- .github/workflows/build.yml
- examples/binary-signing/README.md
- examples/binary-signing/hello-vc.jsonld
- examples/binary-signing/hello.txt
- examples/binary-signing/index.sh
- examples/binary-signing/rdf.awk
- examples/binary-signing/verify.awk
This adds an example of using a Verifiable Credential to assert a content hash and file size.
A shell script uses DIDKit to do signing and verifying, with some AWK for parsing and verifying the claims.
This uses the `didkit to-rdf-urdna2015` subcommand, so includes commits from #172.
> Add binary signing example

- .github/workflows/build.yml
- cli/src/main.rs
- http/src/lib.rs
- lib/src/lib.rs
Integrates <https://github.com/spruceid/ssi/pull/234>.
This should fix the currently failing test in vc-http-api: https://github.com/w3c-ccg/vc-http-api/blob/ca2e216/packages/vc-http-api-test-server/__tests__/issueCredential.spec.js#L72
> 6. The Issuer's Issue Credential HTTP API MUST reject if the value of "options.verificationMethod" in the body of the POST request does not exist.
Update vc-http-api in CI to newer version, to test more things (which should be passing), such as this above test.
> Use URI for verificationMethod option

- .github/workflows/build.yml
- http/tests/vc-http-api/.gitignore
- http/tests/vc-http-api/README.md
- http/tests/vc-http-api/package.json
- http/tests/vc-http-api/test.js
The VC HTTP API Test Suite was split out of the [vc-http-api](https://github.com/w3c-ccg/vc-http-api) repo, into a separate repo, [vc-http-api-test-suite](https://github.com/w3c-ccg/vc-http-api-test-suite/). This PR updates didkit's testing and instructions to use the VC HTTP API Test Suite at its new location.
> Update for separated vc-http-api-test-suite

- lib/ios/Tests/DIDKitSwiftTests/DIDKitTests.swift
The tests for the iOS library was using the wrong `method` and some times, this PR fixes it by changing to `key` method.
Needed for fixing credible's CI https://github.com/spruceid/credible/pull/82
> Fix iOS lib tests

- .github/workflows/build.yml
- lib/node/Cargo.toml
- lib/node/index.d.ts
- lib/node/src/didkit.rs
- lib/node/src/lib.rs
- lib/src/lib.rs
- lib/web/Cargo.toml
- lib/web/src/lib.rs
Exposes ZCAP-LD functionality in `didkit`, `didkit-wasm` and `@spruceid/didkit` using a similar pattern to the VC interface.
Feature flag `delegate`:
- `delegateCapability`
- `prepareDelegateCapability`
- `completeDelegateCapability`
- `verifyDelegation`
Feature flag `invoke`:
- `invokeCapability`
- `prepareInvokeCapability`
- `completeInvokeCapability`
- `verifyInvocationSignature`
- `verifyInvocation`
Feature flag `zcap` enables all functions.
> zcap ld in didkit-wasm

- examples/python_django/README.md
Update README instruction to use DIDKit from PyPI and reword section about manual installation.
> Update README instruction to use DIDKit from PyPI

- cli/README.md
- cli/src/opts.rs
This PR adds a `-R` CLI option to override the DID Resolver with a given DID Resolution (DID URL Dereferencing) HTTP(S) Endpoint, as used in various commands and in the CLI HTTP server. This option is similar to the fallback resolver option (`-r`), but the override resolver is tried first, before the built-in resolvers. If the override resolver  returns error code `methodNotSupported`, resolution proceeds to the built-in resolvers, and then to the fallback resolver (if passed using the `-r` option).
This implements the "easier but more brutish way" of overriding the behavior of the built-in resolvers from [ssi](https://github.com/spruceid/ssi/), as proposed by @vdods in https://github.com/spruceid/didkit/issues/207#issuecomment-916536404.
> Add DID Resolver Override (-R) option

- README.md
instead of pulling breakably from spruceid.dev deployments. Good catch, @clehner !
> Update readme image to be GH hosted

- examples/java-jsp/pom.xml
Updates `lombok` version in Java JSP example to prevent `IllegalAccessError` on newer Java versions.
> Update `lombok` dependency in Java JSP example

- .github/workflows/build.yml
- CHANGELOG.md
- cli/Cargo.toml
- http/Cargo.toml
- lib/Cargo.toml
- lib/node/Cargo.toml
- lib/python/setup.cfg
- lib/src/did_methods.rs
- Update to use ssi v0.3 (https://github.com/spruceid/ssi/pull/296)
- Use VC HTTP API Test Suite with regenerated VP case 2 (https://github.com/w3c-ccg/vc-http-api-test-suite/pull/3)
- Disable `did-sol` until it can be updated to conform with the registered [did:sol specification](https://identity-com.github.io/sol-did/did-method-spec.html)
- Prepare `didkit`~~, `didkit-cli` and `didkit-http` crates~~ for publishing to `crates.io`
> didkit v0.3.0

- cli/Cargo.toml
- http/Cargo.toml
Publish `didkit-cli` and `didkit-http` crates to `crates.io`, using `didkit v0.3.0` (#216).
> DIDKit CLI and HTTP v0.1.1

- lib/flutter/android/src/main/jniLibs/arm64-v8a/libdidkit.so
- lib/flutter/android/src/main/jniLibs/armeabi-v7a/libdidkit.so
- lib/flutter/android/src/main/jniLibs/x86_64/libdidkit.so
- lib/flutter/example/ios/Flutter/Debug.xcconfig
- lib/flutter/example/ios/Flutter/Release.xcconfig
- lib/flutter/example/ios/Podfile
- lib/flutter/example/pubspec.lock
The `libdidkit.so` symlinks on the flutter android lib were pointing to the wrong path.
The final apk generated by an app that embeds didkit flutter library was generated without the needed static libraries.
Fixes spruceid/credible#89
> Fix flutter jniLibs symbolic links

- http/README.md
This is to note that DIDKit HTTP assumes a trusted environment, and that certain security considerations should be addressed in deployments.
> Document DIDKit HTTP security considerations

- lib/Makefile
Fix usage of `$(LIB_NAME)` on `cabi-test` target on `lib/Makefile`.
> Use LIB_NAME on cabi-test

- lib/Makefile
Address #244
The versions changed recently so the currently indicated version does not work.
Available versions can be seen here:
https://github.com/spruceid/didkit/runs/4668134729?check_suite_focus=true#step:6:985
This change removes the version parameter to make the test work with any version.
> Remove iOS version from test

- lib/node/index.d.ts
File `lib/node/index.d.ts` uses the `declare` modifier inside the already `declare`d didkit module and it causes the following errors
Should I provide a repo with a dummy project in order to illustrate the issue more and how to reproduce it ?
> Remove 'declare' modifier in ambient context

- lib/node/README.md
- lib/node/index.d.ts
- lib/node/src/didkit.rs
- lib/node/src/lib.rs
- lib/node/test/index.spec.js
Add `DIDKit.didResolve` function to the Node.js package/module.
> Add DID Resolution to Node package, and rename Node package

- .github/workflows/build.yml
- .github/workflows/push_image.yml
- .github/workflows/smoke_test.yml
Some test failures happen because of environmental/external reasons, so it may be useful to trigger the CI to re-run rather than push another commit.
Also, since the Docker images are published from didkit's main branch and ssi's main branch, it may be useful to be able to trigger a DIDKit Docker image deploy when there are changes in ssi but not in didkit.
> Enable manual dispatch of actions

- .github/workflows/build.yml
Enable tests to pass; as updated in https://github.com/w3c-ccg/vc-api-test-suite/pull/18.
> Use vc-api-test-suite with removed case-29/30

- cli/Cargo.toml
- cli/src/main.rs
- cli/src/opts.rs
- cli/tests/cli.rs
- cli/tests/example.sh
- http/Cargo.toml
- http/src/main.rs
Also move to `clap` v3 (`structopt` has been integrated in `clap`).
---
Here's my proposal for the subcommands.
```
key
├─ generate
├─ secp256k1
├─ ...
├─ did
├─ web
├─ pkh:tz
├─ ...
```
> Add key generation subcommands

- lib/Cargo.toml
- lib/web/Cargo.toml
This is needed for https://github.com/spruceid/ssi/pull/373 / https://github.com/spruceid/ssi/pull/390: the `webkey:gpg` implementation adds default features which must be omitted for wasm.
> Disable did-webkey default features

- .github/workflows/build.yml
- cli/Cargo.toml
- cli/README.md
- cli/src/main.rs
- cli/tests/ion-create-deactivate.sh
- cli/tests/ion-create-recover.sh
- cli/tests/ion-create-update-svc.sh
- cli/tests/ion-create-update-vm.sh
- lib/Cargo.toml
- lib/src/did_methods.rs
- lib/src/error.rs
- lib/src/lib.rs
Integrate Sidetree/ION implementation and DID operations from https://github.com/spruceid/ssi/pull/379.
```
$ didkit generate-secp256k1-key > update0.jwk
$ didkit generate-secp256k1-key > recovery0.jwk
$ didkit generate-secp256k1-key > signing0.jwk
$ did=$(didkit did-create ion -r recovery0.jwk -u update0.jwk -s signing0.jwk)
$ DID_ION_API_URL=http://localhost:3000/ didkit did-resolve "$did"
```
> did:ion and DID operations

- .github/workflows/build.yml
- CHANGELOG.md
- cli/Cargo.toml
- http/Cargo.toml
- lib/Cargo.toml
- lib/node/Cargo.toml
- lib/web/Cargo.toml
Updated to use ssi v0.4 (https://github.com/spruceid/ssi/pull/401).
Changelog updated for changes since v0.3.0.
Updates for new ssi DID method crate versions (https://github.com/spruceid/ssi/pull/403) should not be needed, since the crate versions will still be matched (They are all v0.1.x). `default-features=no` is set for the DID method crates, because of https://github.com/spruceid/ssi/pull/402.
Updated crate versions for publishing:
- didkit v0.4.0
- didkit-cli v0.2.0
- didkit-http v0.2.0
> didkit v0.4.0

- CHANGELOG.md
- lib/Cargo.toml
> didkit v0.3.1

- lib/src/did_methods.rs
Re: https://github.com/spruceid/didkit/issues/138#issuecomment-1097129778
Allow setting any [request proxy URL](https://docs.rs/reqwest/latest/reqwest/struct.Proxy.html) for `did:onion`, via environmental variable 
`DID_ONION_PROXY_URL`. The default value is effectively `socks5h://127.0.0.1:9050/`
> Allow setting did:onion proxy URL

- .github/workflows/build.yml
- cli/src/main.rs
- lib/Cargo.toml
- lib/src/error.rs
- lib/src/lib.rs
- lib/src/ssh_agent.rs
- lib/web/Cargo.toml
- lib/web/src/lib.rs
we should at some point reconsider using `branch = "main"` for the `ssi` crate, any breaking changes pushed to main will break didkit builds everywhere. this pr just fixes builds for the latest update by changing imports and some types, users of the FFI libraries should not notice any breaking changes. notably this pr also slightly reorganises `src/lib/error.rs` to use `thiserror` and expands the set of features to match those of `ssi`. this should resolve #310 and #311 for now, but users will have to change their `p256` feature selection to `secp256r1`. This feature is also now a default.
> update ssi imports and types to post-restructure

- lib/src/c.rs
- macros/src/lib.rs
Removes dependency on didkit_macros from the C API.
Tests covering this are in the didkit-c repo, PR:  https://github.com/spruceid/didkit-c/pull/3
> Remove dependency on macros package from c api

- lib/flutter/lib/didkit.dart
This is the apparent cause of the allocator crash; a subtle bit of API misdesign. We were allocating as many bytes as we had string pointers to store, and then writing full string pointers over top.  This overran the array, stomped the allocator metadata at the beginning of the next thing in memory, and when that thing was returned to the allocator, the integrity checking in the allocator noticed the damage and brought everything down in flames.
> Footgun fix.

- lib/flutter/pubspec.yaml
- lib/ios/Sources/DIDKitSwift/DIDKit.swift
Bump the flutter FFI version to allow for building credible app with newer versions of flutter after: https://github.com/spruceid/credible-mdl/pull/139
Also includes fixes for building with default context loader args.
> 4579767343 -- Feat/bump flutter ffi version

- README.md
I had to fix GitHub workflow badge URL again.
Looks like the changes from [PR #373](https://github.com/spruceid/didkit/pull/373) got undone in [PR #375](https://github.com/spruceid/didkit/pull/375). 
Also, I added new lines between badges to make the diff more readable.
If it doesn't fit the rules for didkit, feel free to close it.
> fix GitHub workflow badge URL again

- http/defaults.toml
This seems to be a simple typo. `http/src/config.rs` has:
```rust
#[serde_as]
#[derive(Deserialize, Debug, Clone, Hash, PartialEq, Eq)]
pub struct Issuer {
#[serde_as(as = "Option<JsonString>")]
pub keys: Option<Vec<JWK>>,
}
```
> Fixing a typo

- Cargo.toml
- README.md
- lib/Cargo.toml
Fixes: https://github.com/spruceid/didkit/issues/389
This PR is the "plan 1" in the "What to do?" section in the https://github.com/spruceid/didkit/issues/389 .
It also fixes a build bug derived from this commit: https://github.com/spruceid/didkit/commit/aacc94fbc16da435527a3ee6a7493516206c7e44
(`http` member must have been removed)
> build(fix): stop using path dependencies to fix corrupt build
