lib/Makefile

Update iOS Target to Match Symlink in Flutter Library

---

.github/workflows/build.yml
README.md

Uses https://github.com/spruceid/ssi/pull/96

Update ssi and use Rust stable

---

.github/workflows/build.yml
lib/Cargo.toml
lib/src/did_methods.rs

Depends on: https://github.com/spruceid/ssi/pull/107

Enable did:sol

---

.github/workflows/build.yml
cli/Cargo.toml
http/Cargo.toml
lib/Cargo.toml
lib/src/did_methods.rs
lib/wasm/Cargo.toml

Relates to https://github.com/spruceid/ssi/pull/98

Update ssi for did:tz

---

examples/java-jsp/.gitignore
examples/java-jsp/README.md
examples/java-jsp/didkit.jar
examples/java-jsp/pom.xml
examples/java-jsp/src/main/java/com/spruceid/java_jsp/ServerSetup.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/Utils.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/model/AuthenticationSubject.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/model/Credential.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/model/Options.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/model/StatusSubject.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/model/Subject.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/CredentialAuthenticationServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/CredentialStatusServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/SignInUsernamePasswordServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/SignInVerifiablePresentationServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/SignOutServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/SignUpServlet.java
examples/java-jsp/src/main/java/com/spruceid/java_jsp/servlet/VersionServlet.java
examples/java-jsp/src/main/webapp/WEB-INF/web.xml
examples/java-jsp/src/main/webapp/chapi.js
examples/java-jsp/src/main/webapp/credential/authentication.jsp
examples/java-jsp/src/main/webapp/credential/display.jsp
examples/java-jsp/src/main/webapp/credential/status.jsp
examples/java-jsp/src/main/webapp/index.jsp
examples/java-jsp/src/main/webapp/sign-in/user-password.jsp
examples/java-jsp/src/main/webapp/sign-in/verifiable-presentation.jsp
examples/java-jsp/src/main/webapp/sign-up.jsp

Add Java JSP Example

---

.github/workflows/build.yml
cli/Cargo.toml
http/Cargo.toml
lib/Cargo.toml
lib/android/README.md
lib/src/did_methods.rs
lib/web/Cargo.toml
lib/web/README.md
lib/web/loader/asmjs/package.json
lib/web/loader/wasm/package-lock.json
lib/web/loader/wasm/package.json
lib/web/loader/wasm/test/index.test.js
lib/web/src/lib.rs

Depends on https://github.com/spruceid/ssi/pull/120
I'm not sure the tests I ran were actually using WASM, is https://github.com/spruceid/didkit/tree/main/lib/web#asm-target relevant to me?

Enable did:tz and did:web for WASM

---

examples/python-flask/README.md
examples/python_django/README.md

In response to https://github.com/spruceid/didkit/issues/106

Add Rust dep to Python example instructions

---

http/tests/vc-http-api/test.js

Increase test timeout for vc-http-api

---

.github/workflows/build.yml
cli/Cargo.toml
cli/src/main.rs
http/Cargo.toml
http/tests/main.rs
lib/Cargo.toml
lib/src/did_methods.rs
lib/web/Cargo.toml

Corresponds to https://github.com/spruceid/ssi/pull/146

Update did-key renamed to did-method-key

---

cli/Cargo.toml
examples/svelte-chapi-wallet/package.json
http/Cargo.toml
http/tests/vc-http-api/package.json
lib/Cargo.toml
lib/cbindings/Cargo.toml
lib/flutter/pubspec.yaml
lib/node/native/Cargo.toml
lib/node/package.json
lib/web/Cargo.toml
lib/web/loader/asmjs/package.json
lib/web/loader/wasm/package.json

Update Cargo package author names to Spruce, as done in https://github.com/spruceid/ssi/pull/137. Similarly update the Node.js packages and the Flutter plugin.

Change authors to Spruce Systems, Inc.

---

cli/README.md
cli/src/main.rs
lib/Cargo.toml
lib/flutter/lib/didkit.dart
lib/java/main/com/spruceid/DIDKit.java
lib/node/native/src/didkit.rs
lib/python/didkit/__init__.py
lib/src/c.rs
lib/src/did_methods.rs
lib/src/jni.rs
lib/web/src/lib.rs

Depends on: #117, https://github.com/spruceid/ssi/pull/124

Add did:pkh

---

.github/workflows/build.yml
lib/Cargo.toml
lib/src/did_methods.rs
lib/web/Cargo.toml

Using https://github.com/spruceid/ssi/pull/167

Update did-tezos crate renamed to did-tz

---

.github/workflows/build.yml
lib/web/loader/wasm/test/index.test.js
lib/web/src/lib.rs

Expose `jwk_from_tezos_key` function added in https://github.com/spruceid/ssi/pull/170

Add JWKFromTezos function in WASM

---

.github/workflows/build.yml
lib/node/Cargo.toml

- Fix path dependency from didkit-node to ssi and didkit
- Update ssi in CI to include https://github.com/spruceid/ssi/pull/200

Update ssi and fix path dependency

---

lib/Makefile
lib/python/.gitignore
lib/python/didkit/__init__.py
lib/python/didkit/tests.py
lib/python/setup.cfg

Changes the names of the functions and parameters used to follow python conventions of snake case.

Renames functions in Python package to follow snake case convention

---

cli/src/main.rs

Currently, if the `SSH_AUTH_SOCK` environmental variable is set (i.e. if `ssh-agent` is running), `didkit-cli` attempts to connect to `ssh-agent` when issuing verifiable credentials and generating verifiable presentations. This is incorrect behavior, leading to errors as seen in https://github.com/spruceid/didkit/pull/172#pullrequestreview-711180387; to reproduce, run `ssh-agent cargo test`. `ssh-agent` should only be used for now if it is specifically called for with the `-S` (`--ssh-agent`) option. If we want to auto-detect if ssh-agent is available, that could be done in some way that does not break existing usage.

Fix CLI ssh-agent option

---

.github/workflows/build.yml
cli/src/main.rs
http/src/lib.rs
lib/node/src/didkit.rs
lib/src/c.rs
lib/src/jni.rs
lib/src/lib.rs
lib/src/ssh_agent.rs
lib/web/src/lib.rs

Integrates https://github.com/spruceid/ssi/pull/261

Pass resolver on issue/prepare

---

.github/workflows/smoke_test.yml

Add scheduled smoke test to install stable didkit

---

CHANGELOG.md

I populated the Unreleased section from all the commit messages since last release

Update didkit changelog

---

CHANGELOG.md

Update changelog for changes since v0.3.0

---

.github/workflows/build.yml
lib/web/src/lib.rs

Address https://github.com/spruceid/didkit/issues/273.
Depends on https://github.com/spruceid/ssi/pull/406.

Add prepareIssuePresentation and completeIssuePresentation to didkit-wasm

---

README.md

- Updates the README to reflect security audit conducted by Trail of Bits

Updated Maturity Disclaimer section

---

lib/node/README.md

Fix module name in node readme

---

.github/workflows/build.yml
cli/src/main.rs
http/src/lib.rs
lib/node/src/didkit.rs
lib/src/c.rs
lib/src/jni.rs
lib/src/lib.rs
lib/src/ssh_agent.rs
lib/web/src/lib.rs

Update for ssi API changes in https://github.com/spruceid/ssi/pull/432

Use ssi ContextLoader

---

cli/Cargo.toml
cli/src/main.rs
cli/tests/cli.rs
http/Cargo.toml
lib/Cargo.toml
lib/src/lib.rs
lib/web/Cargo.toml
lib/web/src/lib.rs

Close https://github.com/spruceid/ssi/issues/481

Update to latest ssi

---

lib/Cargo.toml

Related to https://github.com/spruceid/ssi/pull/484

Remove ssi openssl feature

---

.github/workflows/build.yml
cli/Cargo.toml
cli/src/main.rs
http/tests/vc-api/test.js

Fix DIDKit for latest version of ssi

---

.github/workflows/build.yml

Use rust-cache in CI

---

.github/workflows/build.yml
http/src/main.rs
lib/src/c.rs
lib/src/error.rs
lib/src/ssh_agent.rs

Just fixed a few compilation warnings, mostly from dead code analysis.
There are still warnings about future incompatibilities, but these appear to originate in ssi.

Fix warnings

---

cli/README.md

Fix: typos

---

http/README.md
http/defaults.toml

Update DIDKit HTTP README
